import {
	Home,
	About,
	Login,
	Register,
	QuizzesList,
	Play,
	CreateQuestion,
	CreateQuiz,
	QuestionList,
	/*Preview,
  CreateQuiz,
  CreateQuestion,
  NotFound, */
} from "../components/pages/index";

export const routes = [
	{
		key: "/home",
		path: "/home",
		type: "public",
		name: "Inicio",
		scope: "menu",
		component: Home,
	},
	{
		key: "/about",
		path: "/about",
		type: "public",
		name: "Nosotros",
		scope: "menu",
		component: About,
	},
	{
		key: "/login",
		path: "/login",
		type: "auth",
		mode: "public",
		name: "Ingresar",
		scope: "menu",
		component: Login,
	},
	{
		key: "/register",
		path: "/register",
		type: "auth",
		mode: "public",
		name: "Registrarse",
		scope: "menu",
		component: Register,
	},
	{
		key: "/quizzes",
		path: "/quizzes",
		type: "private",
		name: "Lista de Cuestionarios",
		scope: "menu",
		component: QuizzesList,
	},
	{
		key: "/develop",
		path: "/develop",
		type: "private",
		name: "Crear / Realizar",
		scope: "submenu",
		children: [
			{
				key: "/create-cuestion",
				path: "/develop/create-question",
				type: "private",
				name: "Crear Pregunta",
				component: CreateQuestion,
			},
			{
				key: "/create-option",
				path: "/develop/create-options",
				type: "private",
				name: "Crear Opciones",
				component: CreateQuiz,
			},
			{
				key: "/play",
				path: "/develop/results",
				type: "private",
				name: "Jugar",
				component: Play,
			},
		],
	},
	{
		key: "/results",
		path: "/results",
		type: "private",
		name: "Resultados",
		scope: "submenu",
		children: [
			{
				key: "/options",
				path: "/results/options",
				type: "private",
				name: "Lista de opciones",
				component: QuestionList,
			},
		],
	},
	{
		key: "/logout",
		path: "/logout",
		type: "auth",
		mode: "private",
		name: "Salir",
		scope: "menu",
	},
	{
		key: "/",
		path: "/",
		type: "public",
		scope: "menu",
		pathTo: "/home",
		redirect: true,
	},
	{
		key: "/",
		path: "/",
		type: "private",
		scope: "menu",
		pathTo: "/home",
		redirect: true,
	},
];
